###
GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json
Authorization: bearer yJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im1sdXVra2FpIiwiaWQiOiI2MjRkYzIwYTRiM2RiNjMwM2EwMzE2ZjUiLCJpYXQiOjE2NDkzNTE3MjIsImV4cCI6MTY0OTM1MTc4Mn0.gtNAPTMTy1VsI0E8WfTCaV26jvqZBEEXIxb2O8zjjLQ

{
  "content": "created by",
  "important": true
}

###
PUT http://localhost:3001/api/notes/6245f15ff5276db6aa935363
Content-Type: application/json

{
  "content": "hello world",
  "important": true
}

### 
DELETE http://localhost:3001/api/notes/1

###
GET http://localhost:3001/api/nonexistingroute