###
GET http://localhost:3001/api/notes

###
POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "also created by root/Superuser",
  "important": true,
  "userId": "624dc1504b3db6303a0316ef"
}

###
PUT http://localhost:3001/api/notes/6245f15ff5276db6aa935363
Content-Type: application/json

{
  "content": "hello world",
  "important": true
}

### 
DELETE http://localhost:3001/api/notes/1

###
GET http://localhost:3001/api/nonexistingroute